### ISSUE TITLE
Custom Widgets in PlutoMenuItem

### ISSUE THREAD

**Issue by anlumo** [bosskmk/pluto_menu_bar#7]
Is there a particular reason the API doesn't allow arbitrary widgets in `PlutoMenuItem`s? Judging from a quick look through the source code, it doesn't look like it should be a problem, and it would increase the flexibility by a lot.

The reason for this ticket is that I need a text field and a slider in my menu.

**Comment by bosskmk** [comment]
There are no other reasons.
I'm making it as a hobby, so if there is a user's request, I add a function.
I will update to add other widgets.

**Comment by bosskmk** [comment]
Updated PlutoMenuBar 2.0.2.

https://pluto.weblaze.dev/plutomenuitemwidget

**Comment by anlumo** [comment]
That was very fast! Thank you so much!

I just tried it, seems to work fine so far.
